### ISSUE TITLE
What is the purpose of Tag in Api2Pdf client?

### ISSUE THREAD

**Issue by nheath99** [Api2Pdf/api2pdf.dotnet#1]
https://github.com/Api2Pdf/api2pdf.dotnet/blob/725975e6134e15643df8c1ffb020029fc2fd8d5e/Api2Pdf.DotNet/Api2Pdf.cs#L57

I can't find any documentation for this parameter, from the code above it clearly adds a header to the http request. It would be really useful to display this parameter in the request log.

**Comment by apexdodge** [comment]
@nheath99 it is as you imagine - the tag parameter is supposed to appear if you export your request log to excel.
