### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by jamoZA** [Api2Pdf/api2pdf.dotnet#3]
From 1st March 2020, my Azure Cloud Service deployment using this library started failing using the headless chrome handler.

This was confusing because on my development laptop, the exact same code would work flawlessly.

There was no exception thrown, the call to HeadlessChrome.FromHTML method would just return with an apiResponse with a 

The problem with tracking down the issue is that I could not get a decent exception out of the system. The best I could get was a "one or more errors occurred" by  hacking the PostPdfRequest extension method to separate out the httpClient.PostAsync method and wrapping it in a try/catch block. It seems this is where the problem was.

However, because the above is an asynchronous method, wrapping in a try/catch does not give the correct error - it seems you need to use the method with await in order to correctly catch the exception.

I changed the code to do this and was finally able to catch the above exception (Could not create SSL/TLS secure channel).

The fix for the above exception, if anyone needs it, is as follows:
Add the following line in Api2Pdf.cs just after _httpClient is instantiated:
// Specify to use TLS 1.2 as default connection, otherwise live version on Azure won't connect
                System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12 | System.Net.SecurityProtocolType.Tls11 |
                    System.Net.SecurityProtocolType.Tls;

The code is now working on azure for me but I don't fully understand why the fix above works and I think it would be helpful to modify the methods in this library so that connection errors throw exceptions with useful messages - even just getting the baseurl wrong does not throw a useful exception in my testing.

I think the way to do this is to move to asynchronous calls to httpclient methods wrapped in try/catch blocks. These can then be called either by synchronous or asynchronous methods as the user prefers but at least it means the errors will be meaningful and easier to track down.

If I do this on my version I'll submit changes but at the moment I'm just raising the issue in case it helps someone else who runs into the same thing.

**Comment by apexdodge** [comment]
version 2 released, rewritten library. Not sure if issue is still relevant.

Closing out for now.

Thank you
