### ISSUE TITLE
Allow byte[] when calling convert (libreoffice)

### ISSUE THREAD

**Issue by nickdodd79** [Api2Pdf/api2pdf.dotnet#4]
Hi,

We are currently trialling your service to convert docx reports to pdf (libreoffice). Our process involves using the OpenXML SDK to populate a docx template with various values and then pass the populated file to Api2Pdf to do the conversion. Our API is secured by a JWT token.

Are there any plans to extend your library so a raw byte array can be added to the `Convert()` call instead of a URL. Our issue is that because our API is secured using the Authorization header, the Api2Pdf url call is failing. We have had to implement an elaborate multi-step process to allow access, whereas being able to attach the file bytes to the outgoing `Convert()` call be so much simpler and performant.

Thanks,
Nick.

**Comment by apexdodge** [comment]
Our v2 API allows you to specify custom HTTP headers that are included with the request when pulling the file. So this is the best approach if your API is secured by an authorization header.

v2 documentation:
https://app.swaggerhub.com/apis-docs/api2pdf/api2pdf/2.0.0-beta

See extraHTTPHeaders attribute:
![image](https://user-images.githubusercontent.com/777005/84144739-c80d1080-aa26-11ea-8d1e-7f39b4bfbad9.png)

There are no plans to support direct byte upload.
