### ISSUE TITLE
LibreOffice XLSX headers

### ISSUE THREAD

**Issue by mortenfa** [Api2Pdf/api2pdf.dotnet#7]
Hi,
Im converting a spreadsheet (xlsx) containing our logo in the header. 

All looks ok, but the converter don't recognize the image and the header/footer is empty. Is there any way to include this? 

I'm using the LibreOffice.AnyToPdf method

Thanks

**Comment by apexdodge** [comment]
Not likely, the service is naive in that it just passes the file to LibreOffice for conversion with default settings and does a best effort conversion. WYSIWYG.
